-- Inventory Guide, Slice 0: tables, security rules, and the Tempest seed.
-- Plan: docs/inventory-guide.md. Run ONCE, by Stephen, in the Supabase SQL editor.
--
-- Mirrors the site's existing pattern, read from pg_policies on 2026-10-06:
--   RLS on; anon + authenticated may SELECT, INSERT, UPDATE; NO delete policy, so rows
--   are never deleted (retire with active = false). Ids are identity columns, every
--   table has `location text default 'Tempest'`, and foreign keys name their parents.
--
-- One transaction: if any step fails, or the checks at the end do not match, NOTHING
-- is kept. The last statement prints the row counts.

begin;

-- 1. Storage places, per location, in walking order -----------------------------------
create table public.inventory_places (
  id          bigint generated by default as identity primary key,
  location    text        not null default 'Tempest',
  label       text        not null,
  sort_order  integer     not null default 1000,
  active      boolean     not null default true,
  created_at  timestamptz not null default now()
);
create unique index inventory_places_loc_label on public.inventory_places (location, label);

-- 2. Which order-guide item is counted where. One item may be in more than one place. --
create table public.inventory_items (
  id             bigint generated by default as identity primary key,
  location       text        not null default 'Tempest',
  order_item_id  bigint      not null references public.order_items (id),
  place_id       bigint      not null references public.inventory_places (id),
  sort_order     integer     not null default 1000,
  active         boolean     not null default true,
  created_at     timestamptz not null default now()
);
create unique index inventory_items_one_active_per_place
  on public.inventory_items (place_id, order_item_id) where active = true;

-- 3. One count per month. Only one may be open at a time. -----------------------------
create table public.inventory_counts (
  id          bigint generated by default as identity primary key,
  location    text        not null default 'Tempest',
  period      date        not null check (extract(day from period) = 1),
  status      text        not null default 'open' check (status in ('open', 'closed')),
  closed_at   timestamptz,
  closed_by   text,
  created_at  timestamptz not null default now()
);
create unique index inventory_counts_one_per_month on public.inventory_counts (location, period);
create unique index inventory_counts_one_open on public.inventory_counts (location) where status = 'open';
comment on column public.inventory_counts.period is
  'First day of the month this count closes out: 2026-10-01 = the October month-end count.';

-- 4. What was counted: one row per item-in-a-place, per month. -------------------------
create table public.inventory_count_lines (
  id                 bigint generated by default as identity primary key,
  location           text        not null default 'Tempest',
  count_id           bigint      not null references public.inventory_counts (id),
  inventory_item_id  bigint      not null references public.inventory_items (id),
  full_qty           numeric     check (full_qty >= 0),
  loose_qty          numeric     check (loose_qty >= 0),
  pack_qty_snap      numeric,
  pack_unit_snap     text,
  counted_by         text,
  unit_cost_frozen   numeric,
  value_frozen       numeric,
  value_note         text        check (value_note in ('no price', 'pack changed', 'order units')),
  updated_at         timestamptz not null default now(),
  created_at         timestamptz not null default now()
);
create unique index inventory_count_lines_one_per_item
  on public.inventory_count_lines (count_id, inventory_item_id);
comment on column public.inventory_count_lines.full_qty is
  'Full packs. Both full_qty and loose_qty null = not counted (blank is not zero).';
comment on column public.inventory_count_lines.pack_qty_snap is
  'The price-list pack this line was counted against (e.g. 40). NULL = counted in order-guide units, before the item had a pack; pack_unit_snap then holds that order unit.';
comment on column public.inventory_count_lines.pack_unit_snap is
  'Unit of loose_qty (e.g. lb) at the time of counting, or the order-guide unit when pack_qty_snap is NULL.';
comment on column public.inventory_count_lines.value_frozen is
  'Written at close, from the price list as it stood that day. NULL with a value_note = not valued, never $0.';

-- 5. Close and reopen history. Append-only: no update policy. --------------------------
create table public.inventory_count_log (
  id          bigint generated by default as identity primary key,
  location    text        not null default 'Tempest',
  count_id    bigint      not null references public.inventory_counts (id),
  action      text        not null check (action in ('start', 'close', 'reopen')),
  by_name     text,
  created_at  timestamptz not null default now()
);

-- 6. Security rules (Row Level Security) ----------------------------------------------
alter table public.inventory_places      enable row level security;
alter table public.inventory_items       enable row level security;
alter table public.inventory_counts      enable row level security;
alter table public.inventory_count_lines enable row level security;
alter table public.inventory_count_log   enable row level security;

grant select, insert, update on public.inventory_places, public.inventory_items,
  public.inventory_counts, public.inventory_count_lines to anon, authenticated;
grant select, insert on public.inventory_count_log to anon, authenticated;

create policy inventory_places_select on public.inventory_places for select to anon, authenticated using (true);
create policy inventory_places_insert on public.inventory_places for insert to anon, authenticated with check (true);
create policy inventory_places_update on public.inventory_places for update to anon, authenticated using (true) with check (true);

create policy inventory_items_select on public.inventory_items for select to anon, authenticated using (true);
create policy inventory_items_insert on public.inventory_items for insert to anon, authenticated with check (true);
create policy inventory_items_update on public.inventory_items for update to anon, authenticated using (true) with check (true);

create policy inventory_counts_select on public.inventory_counts for select to anon, authenticated using (true);
create policy inventory_counts_insert on public.inventory_counts for insert to anon, authenticated with check (true);
create policy inventory_counts_update on public.inventory_counts for update to anon, authenticated using (true) with check (true);

-- The freeze: a count line can be added or changed only while its month is open.
create policy inventory_count_lines_select on public.inventory_count_lines for select to anon, authenticated using (true);
create policy inventory_count_lines_insert on public.inventory_count_lines for insert to anon, authenticated
  with check (exists (select 1 from public.inventory_counts c
                      where c.id = inventory_count_lines.count_id and c.status = 'open'));
create policy inventory_count_lines_update on public.inventory_count_lines for update to anon, authenticated
  using      (exists (select 1 from public.inventory_counts c
                      where c.id = inventory_count_lines.count_id and c.status = 'open'))
  with check (exists (select 1 from public.inventory_counts c
                      where c.id = inventory_count_lines.count_id and c.status = 'open'));

create policy inventory_count_log_select on public.inventory_count_log for select to anon, authenticated using (true);
create policy inventory_count_log_insert on public.inventory_count_log for insert to anon, authenticated with check (true);

-- 7. Seed: Tempest's ten places, as Stephen gave them on 2026-10-06 --------------------
insert into public.inventory_places (location, label, sort_order) values
  ($$Tempest$$, $$Vegetable cooler$$, 10),
  ($$Tempest$$, $$Prep/protein cooler$$, 20),
  ($$Tempest$$, $$Fry freezer$$, 30),
  ($$Tempest$$, $$Stand-up freezer$$, 40),
  ($$Tempest$$, $$Dairy coolers$$, 50),
  ($$Tempest$$, $$Dry storage$$, 60),
  ($$Tempest$$, $$Spice shelf$$, 70),
  ($$Tempest$$, $$Vinegar shelf$$, 80),
  ($$Tempest$$, $$Flour shelf$$, 90),
  ($$Tempest$$, $$Line$$, 100);

-- 8. Seed: 216 item-in-place rows (198 items, 18 of them also kept in a second place),
--    from ~/Downloads/inventory_places_approved.csv, approved by Stephen 2026-10-06.
--    Order within a place starts as order-guide order; a manager re-orders it on the page.
insert into public.inventory_items (location, order_item_id, place_id, sort_order)
select $$Tempest$$, v.order_item_id, p.id, v.sort_order
from (values
  (81, $$Vegetable cooler$$, 10),  -- Birite · Dill pickles 5 gal
  (170, $$Vegetable cooler$$, 20),  -- Cooks Produce · Chives
  (171, $$Vegetable cooler$$, 30),  -- Cooks Produce · Cilantro
  (172, $$Vegetable cooler$$, 40),  -- Cooks Produce · Parsley
  (173, $$Vegetable cooler$$, 50),  -- Cooks Produce · Rosemary
  (174, $$Vegetable cooler$$, 60),  -- Cooks Produce · Thyme
  (175, $$Vegetable cooler$$, 70),  -- Cooks Produce · Basil
  (176, $$Vegetable cooler$$, 80),  -- Cooks Produce · Oregano
  (177, $$Vegetable cooler$$, 90),  -- Cooks Produce · Marjoram
  (178, $$Vegetable cooler$$, 100),  -- Cooks Produce · Scallions
  (179, $$Vegetable cooler$$, 110),  -- Cooks Produce · Lemongrass
  (264, $$Vegetable cooler$$, 120),  -- Cooks Produce · Mint
  (183, $$Vegetable cooler$$, 130),  -- Cooks Produce · Lemons
  (184, $$Vegetable cooler$$, 140),  -- Cooks Produce · Limes
  (185, $$Vegetable cooler$$, 150),  -- Cooks Produce · Valencia oranges
  (189, $$Vegetable cooler$$, 160),  -- Cooks Produce · Pineapple
  (265, $$Vegetable cooler$$, 170),  -- Cooks Produce · Melon
  (266, $$Vegetable cooler$$, 180),  -- Cooks Produce · Peach
  (267, $$Vegetable cooler$$, 190),  -- Cooks Produce · Plouts
  (268, $$Vegetable cooler$$, 200),  -- Cooks Produce · Watermelon
  (190, $$Vegetable cooler$$, 210),  -- Cooks Produce · Rocolla
  (191, $$Vegetable cooler$$, 220),  -- Cooks Produce · Baby spinach
  (192, $$Vegetable cooler$$, 230),  -- Cooks Produce · Iceberg
  (193, $$Vegetable cooler$$, 240),  -- Cooks Produce · Baby romaine
  (196, $$Vegetable cooler$$, 250),  -- Cooks Produce · Jalapenos
  (197, $$Vegetable cooler$$, 260),  -- Cooks Produce · Red bell pepper
  (201, $$Vegetable cooler$$, 270),  -- Cooks Produce · Habanero
  (202, $$Vegetable cooler$$, 280),  -- Cooks Produce · Mini mixed peppers
  (203, $$Vegetable cooler$$, 290),  -- Cooks Produce · Fresno chili
  (269, $$Vegetable cooler$$, 300),  -- Cooks Produce · Padron pepper
  (207, $$Vegetable cooler$$, 310),  -- Cooks Produce · Whole garlic bulbs
  (208, $$Vegetable cooler$$, 320),  -- Cooks Produce · Peeled garlic
  (209, $$Vegetable cooler$$, 330),  -- Cooks Produce · Elephant garlic
  (210, $$Vegetable cooler$$, 340),  -- Cooks Produce · Ginger
  (211, $$Vegetable cooler$$, 350),  -- Cooks Produce · Purple ninja radish
  (212, $$Vegetable cooler$$, 360),  -- Cooks Produce · Sm watermelon radish
  (213, $$Vegetable cooler$$, 370),  -- Cooks Produce · Brussels sprouts
  (215, $$Vegetable cooler$$, 380),  -- Cooks Produce · English cucumber
  (216, $$Vegetable cooler$$, 390),  -- Cooks Produce · Celery
  (217, $$Vegetable cooler$$, 400),  -- Cooks Produce · Large carrots
  (218, $$Vegetable cooler$$, 410),  -- Cooks Produce · Mixed large carrots
  (219, $$Vegetable cooler$$, 420),  -- Cooks Produce · Toy box tomato
  (220, $$Vegetable cooler$$, 430),  -- Cooks Produce · Tomatoes 5x6
  (221, $$Vegetable cooler$$, 440),  -- Cooks Produce · Tomatillos
  (222, $$Vegetable cooler$$, 450),  -- Cooks Produce · Fresh horseradish
  (226, $$Vegetable cooler$$, 460),  -- Cooks Produce · Japanese mountain potato
  (270, $$Vegetable cooler$$, 470),  -- Cooks Produce · Heirloom tomato
  (271, $$Vegetable cooler$$, 480),  -- Cooks Produce · Sungold tomato
  (272, $$Vegetable cooler$$, 490),  -- Cooks Produce · White corn
  (273, $$Vegetable cooler$$, 500),  -- Cooks Produce · Yellow corn
  (274, $$Vegetable cooler$$, 510),  -- Cooks Produce · Yellow zucchini
  (233, $$Vegetable cooler$$, 520),  -- Cooks Produce · 4 inch corn tortilla
  (236, $$Vegetable cooler$$, 530),  -- Cooks Produce · Egg roll wrapper
  (168, $$Prep/protein cooler$$, 10),  -- Asia Intl · Skinless pork belly
  (169, $$Prep/protein cooler$$, 20),  -- Asia Intl · Slab bacon
  (281, $$Prep/protein cooler$$, 30),  -- Asia Intl · Duck hearts
  (86, $$Prep/protein cooler$$, 40),  -- Birite · Dry chorizo
  (262, $$Prep/protein cooler$$, 50),  -- Birite · B&B pickles
  (234, $$Prep/protein cooler$$, 60),  -- Cooks Produce · Quail eggs
  (162, $$Prep/protein cooler$$, 70),  -- Schmitz Ranch · Sliced bacon
  (163, $$Prep/protein cooler$$, 80),  -- Schmitz Ranch · Burger meat
  (165, $$Prep/protein cooler$$, 90),  -- Schmitz Ranch · Ribeye select
  (164, $$Prep/protein cooler$$, 100),  -- Schmitz Ranch · B/S chicken breast
  (166, $$Prep/protein cooler$$, 110),  -- Schmitz Ranch · Snls/bnls chicken thigh
  (167, $$Prep/protein cooler$$, 120),  -- Schmitz Ranch · Chicken thigh whole
  (80, $$Fry freezer$$, 10),  -- Birite · Potato FF 3/8
  (281, $$Stand-up freezer$$, 10),  -- Asia Intl · Duck hearts
  (61, $$Stand-up freezer$$, 20),  -- Birite · Flour tortilla
  (82, $$Stand-up freezer$$, 30),  -- Birite · Naan garlic
  (83, $$Stand-up freezer$$, 40),  -- Birite · Amoroso rolls
  (84, $$Stand-up freezer$$, 50),  -- Birite · Pretzel rolls
  (243, $$Stand-up freezer$$, 60),  -- Birite · Veggie chicken
  (260, $$Stand-up freezer$$, 70),  -- Birite · Impossible beef
  (235, $$Stand-up freezer$$, 80),  -- Cooks Produce · Fresh egg noodles
  (165, $$Stand-up freezer$$, 90),  -- Schmitz Ranch · Ribeye select
  (169, $$Dairy coolers$$, 10),  -- Asia Intl · Slab bacon
  (251, $$Dairy coolers$$, 20),  -- Birite · Anchovies
  (89, $$Dairy coolers$$, 30),  -- Birite · Halloumi cheese
  (91, $$Dairy coolers$$, 40),  -- Birite · Toma cheese
  (93, $$Dairy coolers$$, 50),  -- Birite · Mascarpone
  (94, $$Dairy coolers$$, 60),  -- Birite · Parmesan 1/4 wheel
  (95, $$Dairy coolers$$, 70),  -- Birite · Velveeta
  (96, $$Dairy coolers$$, 80),  -- Birite · White cheddar
  (97, $$Dairy coolers$$, 90),  -- Birite · Provolone
  (258, $$Dairy coolers$$, 100),  -- Birite · Blue cheese
  (259, $$Dairy coolers$$, 110),  -- Birite · Feta
  (261, $$Dairy coolers$$, 120),  -- Birite · Manchego
  (180, $$Dairy coolers$$, 130),  -- Cooks Produce · Queso fresco
  (181, $$Dairy coolers$$, 140),  -- Cooks Produce · Shredded jack cheese
  (182, $$Dairy coolers$$, 150),  -- Cooks Produce · Straus Greek yogurt
  (146, $$Dairy coolers$$, 160),  -- Dairy · Gouda (3504)
  (148, $$Dairy coolers$$, 170),  -- Dairy · Toma (3244)
  (151, $$Dairy coolers$$, 180),  -- Dairy · Buttermilk (882)
  (152, $$Dairy coolers$$, 190),  -- Dairy · Whole milk (71)
  (153, $$Dairy coolers$$, 200),  -- Dairy · Heavy cream (1160)
  (154, $$Dairy coolers$$, 210),  -- Dairy · Half & half (1059)
  (155, $$Dairy coolers$$, 220),  -- Dairy · Creme fraiche (1096)
  (156, $$Dairy coolers$$, 230),  -- Dairy · Sour cream (1044)
  (263, $$Dairy coolers$$, 240),  -- Dairy · Greek yogurt (2689)
  (158, $$Dairy coolers$$, 250),  -- Dairy · Eggs (1252)
  (159, $$Dairy coolers$$, 260),  -- Dairy · Horseradish (7510)
  (160, $$Dairy coolers$$, 270),  -- Dairy · Butter (5246)
  (161, $$Dairy coolers$$, 280),  -- Dairy · Pickles (1751)
  (9, $$Dry storage$$, 10),  -- Birite · Kosher salt
  (24, $$Dry storage$$, 20),  -- Birite · Apple cider vinegar
  (25, $$Dry storage$$, 30),  -- Birite · Balsamic vinegar
  (26, $$Dry storage$$, 40),  -- Birite · Champagne vinegar
  (27, $$Dry storage$$, 50),  -- Birite · Fish sauce
  (28, $$Dry storage$$, 60),  -- Birite · Franks Red Hot
  (29, $$Dry storage$$, 70),  -- Birite · Red wine vinegar
  (30, $$Dry storage$$, 80),  -- Birite · Soy sauce
  (31, $$Dry storage$$, 90),  -- Birite · White wine vinegar
  (32, $$Dry storage$$, 100),  -- Birite · Rice wine vinegar
  (33, $$Dry storage$$, 110),  -- Birite · Distilled white vinegar
  (34, $$Dry storage$$, 120),  -- Birite · Sherry vinegar
  (35, $$Dry storage$$, 130),  -- Birite · Grape seed oil
  (36, $$Dry storage$$, 140),  -- Birite · Mirin
  (37, $$Dry storage$$, 150),  -- Birite · Sake
  (249, $$Dry storage$$, 160),  -- Birite · Maggi
  (250, $$Dry storage$$, 170),  -- Birite · Worcestershire
  (40, $$Dry storage$$, 180),  -- Birite · Chipotle peppers
  (41, $$Dry storage$$, 190),  -- Birite · Pepperoncini sliced
  (42, $$Dry storage$$, 200),  -- Birite · Honey
  (43, $$Dry storage$$, 210),  -- Birite · Nonstick spray
  (44, $$Dry storage$$, 220),  -- Birite · Dijon mustard
  (45, $$Dry storage$$, 230),  -- Birite · Whole grain mustard
  (46, $$Dry storage$$, 240),  -- Birite · Ketchup #10 cans
  (47, $$Dry storage$$, 250),  -- Birite · Sriracha
  (51, $$Dry storage$$, 260),  -- Birite · Capers
  (52, $$Dry storage$$, 270),  -- Birite · Corto 51/49
  (53, $$Dry storage$$, 280),  -- Birite · Kombu
  (54, $$Dry storage$$, 290),  -- Birite · Tapatio
  (55, $$Dry storage$$, 300),  -- Birite · Tabasco
  (56, $$Dry storage$$, 310),  -- Birite · Tomato paste
  (57, $$Dry storage$$, 320),  -- Birite · Whole peeled tomatoes
  (58, $$Dry storage$$, 330),  -- Birite · Cherry peppers mild
  (59, $$Dry storage$$, 340),  -- Birite · Sweety drop peppers
  (64, $$Dry storage$$, 350),  -- Birite · Yellow split peas
  (65, $$Dry storage$$, 360),  -- Birite · Elbow noodles
  (67, $$Dry storage$$, 370),  -- Birite · Kewpie mayonnaise
  (252, $$Dry storage$$, 380),  -- Birite · Canned clams
  (253, $$Dry storage$$, 390),  -- Birite · Dukes mayonnaise
  (254, $$Dry storage$$, 400),  -- Birite · Harissa paste
  (255, $$Dry storage$$, 410),  -- Birite · Jalapeno chips
  (256, $$Dry storage$$, 420),  -- Birite · Saltine crackers
  (257, $$Dry storage$$, 430),  -- Birite · Tahini paste
  (227, $$Dry storage$$, 440),  -- Cooks Produce · Yellow onions
  (228, $$Dry storage$$, 450),  -- Cooks Produce · Red onions
  (229, $$Dry storage$$, 460),  -- Cooks Produce · Shallots
  (230, $$Dry storage$$, 470),  -- Cooks Produce · Avocado 60/70ct
  (231, $$Dry storage$$, 480),  -- Cooks Produce · Russet potatoes 90ct
  (232, $$Dry storage$$, 490),  -- Cooks Produce · Sunflower seed
  (237, $$Dry storage$$, 500),  -- Cooks Produce · White sesame seeds
  (238, $$Dry storage$$, 510),  -- Cooks Produce · Black sesame seeds
  (240, $$Dry storage$$, 520),  -- Cooks Produce · Nori
  (275, $$Dry storage$$, 530),  -- Cooks Produce · Beluga lentils
  (276, $$Dry storage$$, 540),  -- Cooks Produce · Dried blueberries
  (277, $$Dry storage$$, 550),  -- Cooks Produce · Dried cranberry beans
  (278, $$Dry storage$$, 560),  -- Cooks Produce · Pistachio
  (279, $$Dry storage$$, 570),  -- Cooks Produce · Quinoa
  (280, $$Dry storage$$, 580),  -- Cooks Produce · Wheat berries
  (149, $$Dry storage$$, 590),  -- Dairy · Clear fry soy (2200)
  (150, $$Dry storage$$, 600),  -- Dairy · Soy bean oil salad (2128)
  (157, $$Dry storage$$, 610),  -- Dairy · Mayo (1252)
  (2, $$Spice shelf$$, 10),  -- Birite · Bay leaves
  (3, $$Spice shelf$$, 20),  -- Birite · Cayenne
  (4, $$Spice shelf$$, 30),  -- Birite · Chili powder
  (5, $$Spice shelf$$, 40),  -- Birite · Onion powder
  (6, $$Spice shelf$$, 50),  -- Birite · Peppercorn
  (7, $$Spice shelf$$, 60),  -- Birite · Red pepper flake
  (8, $$Spice shelf$$, 70),  -- Birite · Ancho powder
  (10, $$Spice shelf$$, 80),  -- Birite · Mustard seeds
  (11, $$Spice shelf$$, 90),  -- Birite · Garlic powder
  (12, $$Spice shelf$$, 100),  -- Birite · Dried oregano, Mexican
  (13, $$Spice shelf$$, 110),  -- Birite · Paprika
  (14, $$Spice shelf$$, 120),  -- Birite · Cinnamon stick
  (15, $$Spice shelf$$, 130),  -- Birite · Nutritional yeast
  (16, $$Spice shelf$$, 140),  -- Birite · Ground cumin
  (17, $$Spice shelf$$, 150),  -- Birite · Dried thyme
  (18, $$Spice shelf$$, 160),  -- Birite · Coriander seeds
  (19, $$Spice shelf$$, 170),  -- Birite · Smoked Maldon salt
  (22, $$Spice shelf$$, 180),  -- Birite · Bubu arare
  (23, $$Spice shelf$$, 190),  -- Birite · Furikake
  (245, $$Spice shelf$$, 200),  -- Birite · Espelette pepper
  (246, $$Spice shelf$$, 210),  -- Birite · Harissa powder
  (247, $$Spice shelf$$, 220),  -- Birite · Mustard powder
  (248, $$Spice shelf$$, 230),  -- Birite · Old Bay
  (198, $$Spice shelf$$, 240),  -- Cooks Produce · Dried chili arbol
  (199, $$Spice shelf$$, 250),  -- Cooks Produce · Dried guajillo chili
  (200, $$Spice shelf$$, 260),  -- Cooks Produce · Dried ancho chili
  (24, $$Vinegar shelf$$, 10),  -- Birite · Apple cider vinegar
  (25, $$Vinegar shelf$$, 20),  -- Birite · Balsamic vinegar
  (26, $$Vinegar shelf$$, 30),  -- Birite · Champagne vinegar
  (27, $$Vinegar shelf$$, 40),  -- Birite · Fish sauce
  (28, $$Vinegar shelf$$, 50),  -- Birite · Franks Red Hot
  (29, $$Vinegar shelf$$, 60),  -- Birite · Red wine vinegar
  (30, $$Vinegar shelf$$, 70),  -- Birite · Soy sauce
  (31, $$Vinegar shelf$$, 80),  -- Birite · White wine vinegar
  (32, $$Vinegar shelf$$, 90),  -- Birite · Rice wine vinegar
  (33, $$Vinegar shelf$$, 100),  -- Birite · Distilled white vinegar
  (34, $$Vinegar shelf$$, 110),  -- Birite · Sherry vinegar
  (36, $$Vinegar shelf$$, 120),  -- Birite · Mirin
  (37, $$Vinegar shelf$$, 130),  -- Birite · Sake
  (249, $$Vinegar shelf$$, 140),  -- Birite · Maggi
  (250, $$Vinegar shelf$$, 150),  -- Birite · Worcestershire
  (68, $$Flour shelf$$, 10),  -- Birite · Baking powder
  (69, $$Flour shelf$$, 20),  -- Birite · Cornmeal
  (70, $$Flour shelf$$, 30),  -- Birite · Cornstarch
  (71, $$Flour shelf$$, 40),  -- Birite · AP flour
  (72, $$Flour shelf$$, 50),  -- Birite · Panko
  (73, $$Flour shelf$$, 60),  -- Birite · Ranch packets
  (74, $$Flour shelf$$, 70),  -- Birite · Rice flour
  (75, $$Flour shelf$$, 80),  -- Birite · White sugar
  (76, $$Flour shelf$$, 90),  -- Birite · Brown sugar
  (77, $$Flour shelf$$, 100),  -- Birite · Baking soda
  (78, $$Flour shelf$$, 110)   -- Birite · Powdered sugar
) as v (order_item_id, place_label, sort_order)
join public.inventory_places p on p.location = 'Tempest' and p.label = v.place_label;

-- 9. Checks. Any mismatch raises an error, and the whole transaction is undone. --------
do $check$
declare n_places int; n_items int; n_distinct int; n_bad int;
begin
  select count(*) into n_places from public.inventory_places where location = 'Tempest';
  select count(*), count(distinct order_item_id) into n_items, n_distinct
    from public.inventory_items where location = 'Tempest';
  select count(*) into n_bad
    from public.inventory_items ii join public.order_items o on o.id = ii.order_item_id
   where ii.location = 'Tempest' and (o.active is not true or o.location is distinct from 'Tempest');
  if n_places <> 10 then raise exception 'expected 10 places, got %', n_places; end if;
  if n_items <> 216 then raise exception 'expected 216 item-in-place rows, got %', n_items; end if;
  if n_distinct <> 198 then raise exception 'expected 198 distinct items, got %', n_distinct; end if;
  if n_bad <> 0 then raise exception '% seeded items are not active Tempest order-guide items', n_bad; end if;
end
$check$;

commit;

-- 10. What you should see: places 10, items 216, counts 0, lines 0, log 0.
select 'inventory_places' as table_name, count(*) as row_count from public.inventory_places
union all select 'inventory_items',       count(*) from public.inventory_items
union all select 'inventory_counts',      count(*) from public.inventory_counts
union all select 'inventory_count_lines', count(*) from public.inventory_count_lines
union all select 'inventory_count_log',   count(*) from public.inventory_count_log;
