-- Inventory Guide, Slice 2: remember what was left off the count on purpose.
-- Plan: docs/inventory-guide.md. Run ONCE, by Stephen, in the Supabase SQL Editor
-- (the source dropdown beside Save must read Database).
--
-- Why: the page lists every NEW order-guide item until a manager gives it a place or
-- taps "Don't count". Without this table, the 56 items left off on purpose would be
-- "new" forever and a genuinely new one would be lost among them.
--
-- Same pattern as Slice 0: RLS on; anon + authenticated may SELECT, INSERT, UPDATE;
-- no delete policy (a decision is undone by active = false, never deleted).
-- One transaction; the check at the end undoes everything unless it matches.

begin;

create table public.inventory_left_off (
  id             bigint generated by default as identity primary key,
  location       text        not null default 'Tempest',
  order_item_id  bigint      not null references public.order_items (id),
  active         boolean     not null default true,
  created_at     timestamptz not null default now()
);
create unique index inventory_left_off_one_active
  on public.inventory_left_off (location, order_item_id) where active = true;

alter table public.inventory_left_off enable row level security;
grant select, insert, update on public.inventory_left_off to anon, authenticated;
create policy inventory_left_off_select on public.inventory_left_off for select to anon, authenticated using (true);
create policy inventory_left_off_insert on public.inventory_left_off for insert to anon, authenticated with check (true);
create policy inventory_left_off_update on public.inventory_left_off for update to anon, authenticated using (true) with check (true);

-- Seed: the 56 active guide items not on the count as of 2026-10-07 — the 48 on
-- non-food shelves (food only was the decision) and the 8 marked Not counted.
insert into public.inventory_left_off (location, order_item_id)
select $$Tempest$$, v.order_item_id
from (values
  (134),  -- Birite · Bar · Box red wine (non-food shelf)
  (135),  -- Birite · Cleaning · Bleach (non-food shelf)
  (136),  -- Birite · Cleaning · Blue scrubby heavy (non-food shelf)
  (137),  -- Birite · Cleaning · Pot & pan soap (non-food shelf)
  (138),  -- Birite · Cleaning · Green scrubby light (non-food shelf)
  (139),  -- Birite · Cleaning · Grill bricks (non-food shelf)
  (140),  -- Birite · Cleaning · SS scrubby (non-food shelf)
  (141),  -- Birite · Cleaning · Black floor mat (non-food shelf)
  (142),  -- Birite · Cleaning · Hand soap (non-food shelf)
  (143),  -- Birite · Equipment · Bread knife 9 inch (non-food shelf)
  (144),  -- Birite · Equipment · Sharpening steel (non-food shelf)
  (145),  -- Birite · Equipment · Non stick pans (non-food shelf)
  (98),  -- Birite · Paper Goods · 12 inch plastic film (non-food shelf)
  (99),  -- Birite · Paper Goods · 18 inch plastic film (non-food shelf)
  (100),  -- Birite · Paper Goods · Bamboo skewer 6 inch (non-food shelf)
  (101),  -- Birite · Paper Goods · Aluminum foil (non-food shelf)
  (102),  -- Birite · Paper Goods · Green tape (non-food shelf)
  (103),  -- Birite · Paper Goods · Large gloves (non-food shelf)
  (104),  -- Birite · Paper Goods · Wooden skewer 4 inch (non-food shelf)
  (105),  -- Birite · Paper Goods · Togo bags (non-food shelf)
  (106),  -- Birite · Paper Goods · 2 oz portion cup (non-food shelf)
  (107),  -- Birite · Paper Goods · 2 oz portion lids (non-food shelf)
  (108),  -- Birite · Paper Goods · Eco box #1 kraft (non-food shelf)
  (109),  -- Birite · Paper Goods · Eco box #3 kraft (non-food shelf)
  (110),  -- Birite · Paper Goods · Parchment paper (non-food shelf)
  (111),  -- Birite · Paper Goods · Deli paper 10x10 (non-food shelf)
  (112),  -- Birite · Paper Goods · Dinner napkins (non-food shelf)
  (113),  -- Birite · Paper Goods · Thermometer (non-food shelf)
  (114),  -- Birite · Paper Goods · Forks compostable (non-food shelf)
  (115),  -- Birite · Paper Goods · Multifold towels (non-food shelf)
  (116),  -- Birite · Paper Goods · Pt containers (non-food shelf)
  (117),  -- Birite · Paper Goods · Qt containers (non-food shelf)
  (118),  -- Birite · Paper Goods · 1/2 pt containers (non-food shelf)
  (119),  -- Birite · Paper Goods · Deli lids (non-food shelf)
  (120),  -- Birite · Paper Goods · Hot cup 16 oz (non-food shelf)
  (121),  -- Birite · Paper Goods · Soup cup lids (non-food shelf)
  (122),  -- Birite · Paper Goods · Knives compostable (non-food shelf)
  (123),  -- Birite · Paper Goods · 1 gal zip lock (non-food shelf)
  (124),  -- Birite · Paper Goods · 2 gal zip lock (non-food shelf)
  (125),  -- Birite · Paper Goods · Spoon compostable (non-food shelf)
  (126),  -- Birite · Paper Goods · Tray 1 lb kraft (non-food shelf)
  (127),  -- Birite · Paper Goods · Container 32 oz rect (non-food shelf)
  (128),  -- Birite · Paper Goods · Tray 3 lb kraft (non-food shelf)
  (129),  -- Birite · Paper Goods · 10 inch plates (non-food shelf)
  (130),  -- Birite · Paper Goods · 6x6 patty paper (non-food shelf)
  (131),  -- Birite · Paper Goods · Hot cup 12 oz (non-food shelf)
  (132),  -- Birite · Paper Goods · Mineral oil slicer (non-food shelf)
  (133),  -- Birite · Paper Goods · Silica packs (non-food shelf)
  (88),  -- Birite · Cooler · Slab bacon (Not counted, approved 2026-10-06)
  (48),  -- Birite · Dry Grocery · Canned root beer (Not counted, approved 2026-10-06)
  (49),  -- Birite · Dry Grocery · Capri Sun (Not counted, approved 2026-10-06)
  (50),  -- Birite · Dry Grocery · Bottle water (Not counted, approved 2026-10-06)
  (66),  -- Birite · Dry Grocery · Coffee (for staff) (Not counted, approved 2026-10-06)
  (186),  -- Cooks Produce · Fruit · Lime juice 1 gal (Not counted, approved 2026-10-06)
  (187),  -- Cooks Produce · Fruit · Grapefruit juice 1/2 gal (Not counted, approved 2026-10-06)
  (188)   -- Cooks Produce · Fruit · Orange juice 1/2 gal (Not counted, approved 2026-10-06)
) as v (order_item_id);

do $check$
declare n int; n_placed int; n_unlisted int;
begin
  select count(*) into n from public.inventory_left_off where location = 'Tempest' and active;
  -- nothing left off may also be on the count
  select count(*) into n_placed from public.inventory_left_off lo
    join public.inventory_items ii on ii.order_item_id = lo.order_item_id and ii.active and ii.location = 'Tempest'
   where lo.active;
  -- every active guide item is now either on the count or left off: nothing is "new"
  select count(*) into n_unlisted from public.order_items o
   where o.location = 'Tempest' and o.active
     and not exists (select 1 from public.inventory_items ii where ii.order_item_id = o.id and ii.active)
     and not exists (select 1 from public.inventory_left_off lo where lo.order_item_id = o.id and lo.active);
  if n <> 56 then raise exception 'expected 56 left-off items, got %', n; end if;
  if n_placed <> 0 then raise exception '% left-off items are also on the count', n_placed; end if;
  if n_unlisted <> 0 then raise exception '% guide items are neither counted nor left off', n_unlisted; end if;
end
$check$;

commit;

-- What you should see: inventory_left_off 56, inventory_items 216.
select 'inventory_left_off' as table_name, count(*) as row_count from public.inventory_left_off
union all select 'inventory_items', count(*) from public.inventory_items;
